### ISSUE TITLE
V1.42 (in VPM Big 1.76) Verzögertes Senden beim Logikausgang führt zu falscher Logikauswertung

### ISSUE THREAD

**Issue by willisurf** [OpenKNX/OAM-LogicModule#12]
Konfiguriert ist ein UND Gatter mit dem zeitversetzten Senden des EIN Signals am Ausgang.
Darauffolgendes AUS führt zu "Verzögerung bleibt bestehen"
Verzögerungszeit 2s, Eingang 1 ist True
Eingang 2 wird kurz EIN geschaltet und innerhalb der 2s wieder ausgeschaltet (roter Pfeil)

Beobachtetes Verhalten: Am Ausgang wird nochmal AUS gesendet und nach 2s schaltet der Ausgang auf EIN und bleibt beliebig lange auf EIN, obwohl die Eingangssignale (Eingang 1 True, Eingang 2 false) bei einem UND ein False erwarten lassen.
![Konfig](https://user-images.githubusercontent.com/101669233/235304560-2ef1394b-be38-4d22-92de-a7e20e5e5ca0.jpg)
![GAs](https://user-images.githubusercontent.com/101669233/235304568-7b9ce7ce-d759-4b23-a161-00de151fee09.jpg)
![GrpMon](https://user-images.githubusercontent.com/101669233/235304575-fd5af545-2717-485f-b481-6ddc3a0a30e6.jpg)

**Comment by mumpf** [comment]
Works as Designed :-) 
Folgendes läuft: 

- Der AUSGANG vom UND geht auf EIN
- Das EIN-Signal wird für 2 Sekunden verzögert
- Nach 1.2 Sekunden geht der AUSGANG vom UND auf AUS.
- Das AUS-Signal wird nicht verzögert und soll gesendet werden, also wird AUS gesendet.
- Nach weiteren 0.8 Sekunden wird das EIN-Signal gesendet
- Es kommen keine weiteren Signale, also ist das der finale Zustand.

Es ist genau das, was Du eingestellt hast. Wenn das AUS das EIN verhindern soll, musst Du "Darauffolgendes AUS führt zu Verzögerunge beenden ohne zu schalten" auswählen. Du scheinst das zu erwarten.

Falls ich es missverstanden habe, bitte neu eröffnen.
