### ISSUE TITLE
Bug: Anzeige "Kommunikationsobjekt für Ausgang" fehlerhaft.

### ISSUE THREAD

**Issue by traxanos** [OpenKNX/OAM-LogicModule#3]
Die Zahlenausgabe "Kommunikationsobjekt für Ausgang" enden bei 999. Bei höheren Logikkanälen ist der Zahl somit falsch.

Beispiel bei Logik 99 wird die 999 ausgegeben, aber die KO Nummer ist: 1146.

**Comment by mumpf** [comment]
Hi, vergessen das zu schließen...
Ist mit v1.0 behoben.
