### ISSUE TITLE
DPT5.001 wird falsch (nicht?) konvertiert

### ISSUE THREAD

**Issue by ginkel** [OpenKNX/OAM-LogicModule#8]
Hallo,

ich beobachte aktuell falsche Ergebnisse bei Logikkanälen, die den Durchschnitt auf zwei DPT5.001-Eingängen berechnen. Parametriert ist das Ganze wie folgt:

![image](https://user-images.githubusercontent.com/174129/210116600-824e6fed-ee93-4350-aa6c-177b04b45c19.png)

![image](https://user-images.githubusercontent.com/174129/210116615-8e84f206-9bd5-4a39-9136-3baf54c8a10a.png)

![image](https://user-images.githubusercontent.com/174129/210116622-9d0b0f20-4809-4356-b95d-e611bea43e1f.png)

![image](https://user-images.githubusercontent.com/174129/210116637-baa6dd87-8543-4d7a-9634-138c46012501.png)

![image](https://user-images.githubusercontent.com/174129/210116657-2b863d51-8684-4437-8ae6-c3789d0c4aff.png)

Schreibe ich nun auf die beiden Eingänge 100%, erhalte ich als Ergebnis 39%:

![image](https://user-images.githubusercontent.com/174129/210116684-6d33846b-fe2c-4681-8b91-749b5f053d55.png)

Möglich, dass andere Funktionen/Operationen/Datentypen ebenfalls betroffen sind - bei den Prozenten war es bislang am einfachsten nachzuvollziehen, da das Ergebnis so gar nicht zum Zustand der Rollos passen will. ;-)

Firmware ist OAM-PresenceModule 1.5 mit passender Applikation.

Danke & viele Grüße
Thilo

Edit: Ich könnte mir vorstellen, dass das mit den Änderungen aus 12d419cb027fba85429aa86a1ce356544a5c16a6 zu tun hat...

**Comment by mumpf** [comment]
Danke für die Rückmeldung. 

Verstehe ich Dich richtig? Das ging früher und geht jetzt nicht mehr? Dann muss ich den Fall mal checken. DPT5.001 bring ja immer Probleme, aber hier muss ich erstmal verstehen, was da passiert. 
Es liegt sicherlich an den Änderungen, die Du referenzierst, aber die werde ich nicht zurücknehmen, denn das ist der "richtige" Weg voran. 
Wir finden sicherlich eine Korrektur, aber erst nächstes Jahr :-)

**Comment by ginkel** [comment]
Genauso ist es. Ich hatte zuvor das PresenceModule-Big-1.4 in Betrieb mit ein paar Logikkanälen, die die gemittelte Position der Rollos in einigen Räumen ausrechnen (um irgendwas halbwegs sinnvolles auf dem Glastaster anzeigen zu können). Das lief soweit. Hatte dann vor Weihnachten auf die 1.5 upgedated. Gestern habe ich dann eine Erweiterung vorgenommen, deren Ergebnisse unplausibel waren. Da fiel mir dann auf, dass auch die "alten" Kanäle kein korrektes Ergebnis mehr liefern.

Das Beispiel von oben ist ein minimaler Reproducer, der auf das nötigste reduziert ist. Je länger ich drüber nachdenke, desto sicherer bin ich mir, dass der Durchschnitt vmtl. nichts damit zu tun hat.

Ich habe das Ganze gerade noch einmal reduziert. Ausgang = E1:

![image](https://user-images.githubusercontent.com/174129/210134812-9f1942ce-4230-4ce5-9ccd-751b5a64019d.png)

Selbst da treten dieselben Fehler auf.

E1=0xFF, A=0x64
E1=0x80, A=0x32
E1=0x33, A=0x14

Danke für deine Unterstützung und schon mal einen guten Rutsch nach 2023!

**Comment by ginkel** [comment]
Noch ein Update: Das ist AFAICS ein Fehler im Konverter. 100 == 0x64, d.h., da wird der Wertebereich nicht mehr auf 0..255 gewandelt, sondern verbleibt bei 0..100.

**Comment by mumpf** [comment]
Hi, ich habe heute einen Fehler im Ausgangskonverter gefunden, der das von Dir beschriebene Symptom verursacht hat. 
Die Korrektur wird im nächsten Release vom Logikmodul enthalten sein (Release-1.2).

**Comment by ginkel** [comment]
Perfekt, vielen Dank!

**Comment by ginkel** [comment]
Kurze Rückmeldung: Funktioniert jetzt einwandfrei, vielen Dank!
